### ISSUE TITLE
issue: /// Lines beginning with `#` are ignored

### ISSUE THREAD

**Issue by mhmoudgmal** [museun/configurable#4]
Hi there! :)

I came across your repo as I was doing something similar to the **load** fn [here](https://github.com/museun/configurable/blob/4fce6a8cf9b932a0fc3f268c51587b1d36e7f610/src/env.rs#L22)

I think if the goal was to ignore the lines begin with `#` then the filter here 
https://github.com/museun/configurable/blob/4fce6a8cf9b932a0fc3f268c51587b1d36e7f610/src/env.rs#L29

should be like:

```
.filter(|s| !s.starts_with('#'))
```

Thanks.

**Comment by museun** [comment]
Ah, it bites me again. I always get the _language_ of filter backwards. its `false` to exclude it, not `true` to _filter it out_. Thanks, I'll fix that. 

I have it correct here, if you're interested in something with just envs.
https://github.com/museun/simple_env_load/blob/9c4e7c28b95323fb07073f6433ccba2d5bc5620d/src/lib.rs#L63-L76

**Comment by mhmoudgmal** [comment]
Thank you!

Yes I understand it can be confusing, I think one way to ensure the correctness of the logic is to test it, so maybe having unit tests will help.
